// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Prekrasna vila s 4 spavaće sobe i privatnim bazenom, idealna za obiteljski odmor.\r\nSmještena u mirnom okruženju, samo 50 metara od plaže.\r\nVila nudi savršen spoj moderne opreme i tradicionalnog dalmatinskog stila.\r\n",
                            ImageUrl = "",
                            Name = "King vila",
                            Occupancy = 5,
                            Rate = 2000.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Prekrasna vila s 4 spavaće sobe i privatnim bazenom, idealna za obiteljski odmor.\r\nSmještena u mirnom okruženju, samo 50 metara od plaže.\r\nVila nudi savršen spoj moderne opreme i tradicionalnog dalmatinskog stila.\r\n",
                            ImageUrl = "",
                            Name = "King vila 2",
                            Occupancy = 5,
                            Rate = 1000.0,
                            Sqft = 300,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Prekrasna vila s 4 spavaće sobe i privatnim bazenom, idealna za obiteljski odmor.\r\nSmještena u mirnom okruženju, samo 50 metara od plaže.\r\nVila nudi savršen spoj moderne opreme i tradicionalnog dalmatinskog stila.\r\n",
                            ImageUrl = "",
                            Name = "King vila 3",
                            Occupancy = 4,
                            Rate = 1200.0,
                            Sqft = 350,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Prekrasna vila s 4 spavaće sobe i privatnim bazenom, idealna za obiteljski odmor.\r\nSmještena u mirnom okruženju, samo 50 metara od plaže.\r\nVila nudi savršen spoj moderne opreme i tradicionalnog dalmatinskog stila.\r\n",
                            ImageUrl = "",
                            Name = "King vila 4",
                            Occupancy = 3,
                            Rate = 800.0,
                            Sqft = 200,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Prekrasna vila s 4 spavaće sobe i privatnim bazenom, idealna za obiteljski odmor.\r\nSmještena u mirnom okruženju, samo 50 metara od plaže.\r\nVila nudi savršen spoj moderne opreme i tradicionalnog dalmatinskog stila.\r\n",
                            ImageUrl = "",
                            Name = "King vila 5",
                            Occupancy = 5,
                            Rate = 1400.0,
                            Sqft = 900,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Prekrasna vila s 4 spavaće sobe i privatnim bazenom, idealna za obiteljski odmor.\r\nSmještena u mirnom okruženju, samo 50 metara od plaže.\r\nVila nudi savršen spoj moderne opreme i tradicionalnog dalmatinskog stila.\r\n",
                            ImageUrl = "",
                            Name = "King vila 6",
                            Occupancy = 5,
                            Rate = 1000.0,
                            Sqft = 300,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
